#!/usr/bin/env node

/**
 * Build Configuration Script
 * 
 * Reads environment variables from .env file and generates config/env.js
 * Usage: node scripts/build-config.js [environment]
 * 
 * Examples:
 *   node scripts/build-config.js development
 *   node scripts/build-config.js staging
 *   node scripts/build-config.js production
 */

const fs = require('fs');
const path = require('path');

const ENV_PRESETS = {
  development: {
    ENV: 'development',
    API_BASE_URL: 'http://localhost:8080/api/v1',
    TIMEOUT: '10000',
    RETRY_ATTEMPTS: '2',
    RETRY_DELAY: '1000',
  },
  staging: {
    ENV: 'staging',
    API_BASE_URL: 'https://staging-api.example.com/api/v1',
    TIMEOUT: '15000',
    RETRY_ATTEMPTS: '3',
    RETRY_DELAY: '1500',
  },
  production: {
    ENV: 'production',
    API_BASE_URL: 'https://api.example.com/api/v1',
    TIMEOUT: '15000',
    RETRY_ATTEMPTS: '3',
    RETRY_DELAY: '2000',
  },
};

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) {
    return null;
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  const env = {};

  content.split('\n').forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;

    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      env[key.trim()] = valueParts.join('=').trim();
    }
  });

  return env;
}

function generateConfigFile(config) {
  const template = `/**
 * Environment Configuration
 * 
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/build-config.js
 * 
 * To change configuration:
 * 1. Edit .env file or use environment presets
 * 2. Run: npm run config:dev (or config:staging, config:prod)
 */

const CURRENT_ENV = '${config.ENV}';

const environments = {
  development: {
    apiBaseURL: '${config.ENV === 'development' ? config.API_BASE_URL : ENV_PRESETS.development.API_BASE_URL}',
    timeout: ${config.ENV === 'development' ? config.TIMEOUT : ENV_PRESETS.development.TIMEOUT},
    retryAttempts: ${config.ENV === 'development' ? config.RETRY_ATTEMPTS : ENV_PRESETS.development.RETRY_ATTEMPTS},
    retryDelay: ${config.ENV === 'development' ? config.RETRY_DELAY : ENV_PRESETS.development.RETRY_DELAY},
  },
  staging: {
    apiBaseURL: '${config.ENV === 'staging' ? config.API_BASE_URL : ENV_PRESETS.staging.API_BASE_URL}',
    timeout: ${config.ENV === 'staging' ? config.TIMEOUT : ENV_PRESETS.staging.TIMEOUT},
    retryAttempts: ${config.ENV === 'staging' ? config.RETRY_ATTEMPTS : ENV_PRESETS.staging.RETRY_ATTEMPTS},
    retryDelay: ${config.ENV === 'staging' ? config.RETRY_DELAY : ENV_PRESETS.staging.RETRY_DELAY},
  },
  production: {
    apiBaseURL: '${config.ENV === 'production' ? config.API_BASE_URL : ENV_PRESETS.production.API_BASE_URL}',
    timeout: ${config.ENV === 'production' ? config.TIMEOUT : ENV_PRESETS.production.TIMEOUT},
    retryAttempts: ${config.ENV === 'production' ? config.RETRY_ATTEMPTS : ENV_PRESETS.production.RETRY_ATTEMPTS},
    retryDelay: ${config.ENV === 'production' ? config.RETRY_DELAY : ENV_PRESETS.production.RETRY_DELAY},
  },
};

const currentConfig = environments[CURRENT_ENV] || environments.development;

module.exports = {
  env: CURRENT_ENV,
  apiBaseURL: currentConfig.apiBaseURL,
  timeout: currentConfig.timeout,
  retryAttempts: currentConfig.retryAttempts,
  retryDelay: currentConfig.retryDelay,
};
`;

  return template;
}

function main() {
  const args = process.argv.slice(2);
  const targetEnv = args[0] || 'development';

  if (!ENV_PRESETS[targetEnv]) {
    console.error(`❌ Invalid environment: ${targetEnv}`);
    console.error(`   Valid options: ${Object.keys(ENV_PRESETS).join(', ')}`);
    process.exit(1);
  }

  console.log(`🔧 Building configuration for: ${targetEnv}`);

  const envFilePath = path.join(__dirname, '..', '.env');
  let config = { ...ENV_PRESETS[targetEnv] };

  const envFileConfig = parseEnvFile(envFilePath);
  if (envFileConfig) {
    console.log(`📄 Found .env file, merging with preset...`);
    config = { ...config, ...envFileConfig };
  } else {
    console.log(`📄 No .env file found, using preset values`);
  }

  const configContent = generateConfigFile(config);
  const outputPath = path.join(__dirname, '..', 'config', 'env.js');

  const configDir = path.dirname(outputPath);
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, configContent, 'utf-8');

  console.log(`✅ Configuration generated successfully!`);
  console.log(`   Environment: ${config.ENV}`);
  console.log(`   API Base URL: ${config.API_BASE_URL}`);
  console.log(`   Output: config/env.js`);
}

main();
